import {
  BookMarked,
  Brain,
  Camera,
  Cpu,
  Download,
  GripVertical,
  Layers,
  Play,
  Sparkles,
  Type,
  Wand2,
  Zap,
} from "lucide-react";

import type { TourStep } from "./types";

export const tourSteps: TourStep[] = [
  {
    id: "welcome",
    title: "Welcome to Nano Flow",
    description: "Your batch processing powerhouse for Gemini. Let's take a quick tour!",
    icon: <Sparkles className="h-5 w-5" />,
    selector: "[data-onboarding='sidebar-header']",
    tab: "queue",
    position: "bottom",
  },
  {
    id: "textarea",
    title: "Add Your Prompts",
    description:
      "Enter multiple prompts here, one per paragraph. Press Ctrl+Enter to add them to the queue.",
    icon: <Type className="h-5 w-5" />,
    selector: "[data-onboarding='queue-textarea']",
    tab: "queue",
    position: "top",
    spotlightPadding: 8,
  },
  {
    id: "tool-selector",
    title: "Choose Your Tool",
    description:
      "Select Image, Video, Canvas, or other tools. Each prompt can use a different tool.",
    icon: <Camera className="h-5 w-5" />,
    selector: "[data-onboarding='tool-selector']",
    tab: "queue",
    position: "top",
  },
  {
    id: "add-queue",
    title: "Build Your Queue",
    description: "Click here to add prompts to the queue. Import CSV for bulk uploads with images.",
    icon: <Layers className="h-5 w-5" />,
    selector: "[data-onboarding='add-queue-btn']",
    tab: "queue",
    position: "top",
  },
  {
    id: "start-engine",
    title: "Start Processing",
    description:
      "Hit this button to start batch processing. Watch as prompts are generated automatically!",
    icon: <Play className="h-5 w-5" />,
    selector: "[data-onboarding='start-button']",
    tab: "queue",
    position: "top",
  },
  {
    id: "queue-list",
    title: "Monitor Progress",
    description: "Your queue items appear here. Drag to reorder, edit, duplicate, or remove items.",
    icon: <Cpu className="h-5 w-5" />,
    selector: "[data-onboarding='queue-list']",
    tab: "queue",
    position: "top",
    spotlightPadding: 8,
  },
  {
    id: "drag-reorder",
    title: "Drag to Reorder",
    description:
      "Grab the handle on any item to drag and drop it into a new position in your queue.",
    icon: <GripVertical className="h-5 w-5" />,
    selector: "[data-onboarding='queue-list']",
    tab: "queue",
    position: "top",
  },
  {
    id: "export-queue",
    title: "Export Your Work",
    description:
      "Download your queue as TXT, JSON, or CSV. Great for backing up or sharing prompts.",
    icon: <Download className="h-5 w-5" />,
    selector: "[data-onboarding='start-button']",
    tab: "queue",
    position: "top",
  },
  {
    id: "templates",
    title: "Save Your Favorites",
    description: "Organize prompts into folders. Reuse templates and reference images instantly.",
    icon: <BookMarked className="h-5 w-5" />,
    selector: "[data-onboarding='templates-panel']",
    tab: "templates",
    position: "right",
    spotlightPadding: 8,
  },
  {
    id: "ai-optimize",
    title: "AI Enhancement",
    description:
      "Click the wand icon on any template to let AI improve your prompts automatically.",
    icon: <Wand2 className="h-5 w-5" />,
    selector: "[data-onboarding='templates-panel']",
    tab: "templates",
    position: "right",
  },
  {
    id: "tool-selector-2",
    title: "Choose Your Tool",
    description:
      "Select Image, Video, Canvas, or other tools. Each prompt can use a different tool.",
    icon: <Camera className="h-5 w-5" />,
    selector: "[data-onboarding='tool-selector']",
    tab: "queue",
    position: "top",
  },
  {
    id: "mode-selector",
    title: "Select Response Mode",
    description:
      "Choose Quick for speed, Deep for thorough thinking, or Pro for highest quality output.",
    icon: <Brain className="h-5 w-5" />,
    selector: "[data-onboarding='mode-selector']",
    tab: "queue",
    position: "top",
  },
  {
    id: "model-selector",
    title: "Choose Your Model",
    description: "Flash 2.0 for speed, Imagen 3 for quality. Pick what suits your needs.",
    icon: <Zap className="h-5 w-5" />,
    selector: "[data-onboarding='model-selector']",
    tab: "settings",
    position: "top",
  },
  {
    id: "theme-system",
    title: "Auto Theme Sync",
    description: "Choose System theme to automatically match your browser's light/dark preference.",
    icon: <Sparkles className="h-5 w-5" />,
    selector: "[data-onboarding='theme-selector']",
    tab: "settings",
    position: "top",
  },
];
