// Generated by wxt
export {}
declare global {
  const ApiKeyDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/ApiKeyDialog')['default']
  const BulkActionsDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/BulkActionsDialog')['default']
  const BulkDownloadButton: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/BulkDownloadButton')['default']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const CsvDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/CsvDialog')['default']
  const ExportDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/ExportDialog')['default']
  const Footer: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/Footer')['default']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const OnboardingModal: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/OnboardingModal')['default']
  const QueueItemCard: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/QueueItemCard')['default']
  const QueuePanel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/QueuePanel')['default']
  const SearchFilter: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/SearchFilter')['default']
  const SettingsPanel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/SettingsPanel')['default']
  const StatusBadge: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/StatusBadge')['default']
  const TemplatesPanel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/TemplatesPanel')['default']
  const Tooltip: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/Tooltip')['default']
  const browser: typeof import('wxt/browser')['browser']
  const clickNativeDownloadButton: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['clickNativeDownloadButton']
  const constructFinalPrompt: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useQueue')['constructFinalPrompt']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createQueueItems: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useQueue')['createQueueItems']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const downloadAllMedia: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['downloadAllMedia']
  const downloadAllViaNativeButtons: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['downloadAllViaNativeButtons']
  const downloadMedia: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['downloadMedia']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const findAllMedia: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findAllMedia']
  const findDownloadableFiles: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findDownloadableFiles']
  const findGeneratedImages: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findGeneratedImages']
  const findGeneratedVideos: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findGeneratedVideos']
  const injectScript: typeof import('wxt/client')['injectScript']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useMemo: typeof import('react')['useMemo']
  const useQueue: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useQueue')['default']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useStorage: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useStorage')['default']
  const useStorageListener: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useStorage')['useStorageListener']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ResetFilter } from '/Applications/Github/extension-gemini-auto-queue/src/components/BulkActionsDialog'
  import('/Applications/Github/extension-gemini-auto-queue/src/components/BulkActionsDialog')
  // @ts-ignore
  export type { MediaItem } from '/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader'
  import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')
}
