// Generated by wxt
export {}
declare global {
  const ASPECT_RATIOS: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imagePresets')['ASPECT_RATIOS']
  const ApiKeyDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/ApiKeyDialog')['default']
  const BulkActionsDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/BulkActionsDialog')['default']
  const BulkDownloadButton: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/BulkDownloadButton')['default']
  const BulkDownloadDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/BulkDownloadDialog')['default']
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const CsvDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/CsvDialog')['default']
  const ExportDialog: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/ExportDialog')['default']
  const FORMAT_INFO: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imagePresets')['FORMAT_INFO']
  const Footer: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/Footer')['default']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const LogLevel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/logger')['LogLevel']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const OnboardingModal: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/OnboardingModal')['default']
  const QUICK_PRESETS: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imagePresets')['QUICK_PRESETS']
  const QueueItemCard: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/QueueItemCard')['default']
  const QueuePanel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/QueuePanel')['default']
  const SELECTORS: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/selectors')['SELECTORS']
  const SIZE_PRESETS: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imagePresets')['SIZE_PRESETS']
  const SearchFilter: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/SearchFilter')['default']
  const SettingsPanel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/SettingsPanel')['default']
  const StatusBadge: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/StatusBadge')['default']
  const TOOL_SELECTORS: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/selectors')['TOOL_SELECTORS']
  const TemplatesPanel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/TemplatesPanel')['default']
  const Tooltip: typeof import('/Applications/Github/extension-gemini-auto-queue/src/components/Tooltip')['default']
  const base64ToFile: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['base64ToFile']
  const browser: typeof import('wxt/browser')['browser']
  const buildGoogleImageUrl: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/googleImageUrl')['buildGoogleImageUrl']
  const calculateBackoff: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/retryStrategy')['calculateBackoff']
  const canUseServerSideProcessing: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/googleImageUrl')['canUseServerSideProcessing']
  const categorizeError: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/retryStrategy')['categorizeError']
  const clickElement: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['clickElement']
  const clickNativeDownloadButton: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['clickNativeDownloadButton']
  const constructFinalPrompt: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useQueue')['constructFinalPrompt']
  const countExpandedPrompts: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/variableExpander')['countExpandedPrompts']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createQueueItems: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useQueue')['createQueueItems']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const delay: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/timing')['delay']
  const downloadAllMedia: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['downloadAllMedia']
  const downloadAllViaNativeButtons: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['downloadAllViaNativeButtons']
  const downloadBlob: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imageProcessor')['downloadBlob']
  const downloadFromUrl: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imageProcessor')['downloadFromUrl']
  const downloadMedia: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['downloadMedia']
  const downloadSingleFile: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/batchProcessor')['downloadSingleFile']
  const expandPromptWithVariables: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/variableExpander')['expandPromptWithVariables']
  const expandVariables: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/variableExpander')['expandVariables']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const findAllMedia: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findAllMedia']
  const findByAriaLabel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['findByAriaLabel']
  const findByText: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['findByText']
  const findDownloadableFiles: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findDownloadableFiles']
  const findElement: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['findElement']
  const findElements: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['findElements']
  const findGeneratedImages: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findGeneratedImages']
  const findGeneratedVideos: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')['findGeneratedVideos']
  const formatRetryDelay: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/retryStrategy')['formatRetryDelay']
  const getAspectRatioById: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imagePresets')['getAspectRatioById']
  const getErrorCategoryLabel: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/retryStrategy')['getErrorCategoryLabel']
  const getExtFromMime: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['getExtFromMime']
  const getMimeFromBase64: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['getMimeFromBase64']
  const getPresetById: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imagePresets')['getPresetById']
  const getPresetsByCategory: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imagePresets')['getPresetsByCategory']
  const injectScript: typeof import('wxt/client')['injectScript']
  const isGoogleCdnUrl: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/googleImageUrl')['isGoogleCdnUrl']
  const logger: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/logger')['logger']
  const parseInlineVariables: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/variableExpander')['parseInlineVariables']
  const parseVariableReferences: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/variableExpander')['parseVariableReferences']
  const processBatch: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/batchProcessor')['processBatch']
  const processWithCanvas: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/imageProcessor')['processWithCanvas']
  const shouldRetry: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/retryStrategy')['shouldRetry']
  const sleep: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/timing')['sleep']
  const storage: typeof import('wxt/storage')['storage']
  const stripGoogleUrlParams: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/googleImageUrl')['stripGoogleUrlParams']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useEffect: typeof import('react')['useEffect']
  const useFormSubmit: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useFormSubmit')['useFormSubmit']
  const useMemo: typeof import('react')['useMemo']
  const useQueue: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useQueue')['default']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useState: typeof import('react')['useState']
  const useStorage: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useStorage')['default']
  const useStorageListener: typeof import('/Applications/Github/extension-gemini-auto-queue/src/hooks/useStorage')['useStorageListener']
  const waitForElement: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/index')['waitForElement']
  const waitUntil: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/timing')['waitUntil']
  const withTimeout: typeof import('/Applications/Github/extension-gemini-auto-queue/src/utils/timing')['withTimeout']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { ResetFilter, ChatMediaCounts } from '/Applications/Github/extension-gemini-auto-queue/src/components/BulkActionsDialog'
  import('/Applications/Github/extension-gemini-auto-queue/src/components/BulkActionsDialog')
  // @ts-ignore
  export type { BatchOptions } from '/Applications/Github/extension-gemini-auto-queue/src/utils/batchProcessor'
  import('/Applications/Github/extension-gemini-auto-queue/src/utils/batchProcessor')
  // @ts-ignore
  export type { LogLevel, LogEntry, ModuleLogger } from '/Applications/Github/extension-gemini-auto-queue/src/utils/logger'
  import('/Applications/Github/extension-gemini-auto-queue/src/utils/logger')
  // @ts-ignore
  export type { MediaItem } from '/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader'
  import('/Applications/Github/extension-gemini-auto-queue/src/utils/mediaDownloader')
  // @ts-ignore
  export type { SelectorKey } from '/Applications/Github/extension-gemini-auto-queue/src/utils/selectors'
  import('/Applications/Github/extension-gemini-auto-queue/src/utils/selectors')
  // @ts-ignore
  export type { ParsedVariable } from '/Applications/Github/extension-gemini-auto-queue/src/utils/variableExpander'
  import('/Applications/Github/extension-gemini-auto-queue/src/utils/variableExpander')
}
