import React from "react";

import { QueueStatus } from "@/types";

interface StatusBadgeProps {
  status: QueueStatus;
  errorMessage?: string;
}

const statusStyles: Record<QueueStatus, string> = {
  [QueueStatus.Pending]: "bg-amber-100 text-amber-600",
  [QueueStatus.Processing]: "bg-blue-100 text-blue-600 animate-pulse",
  [QueueStatus.Completed]: "bg-emerald-100 text-emerald-600",
  [QueueStatus.Failed]: "bg-red-100 text-red-600",
};

const statusDescriptions: Record<QueueStatus, string> = {
  [QueueStatus.Pending]: "Waiting in queue to be processed",
  [QueueStatus.Processing]: "Currently being generated by Gemini",
  [QueueStatus.Completed]: "Successfully completed",
  [QueueStatus.Failed]: "Generation failed - check Gemini for errors",
};

export const StatusBadge: React.FC<StatusBadgeProps> = ({ status, errorMessage }) => {
  const tooltipText =
    status === QueueStatus.Failed && errorMessage
      ? `Error: ${errorMessage}`
      : statusDescriptions[status];

  return (
    <div
      title={tooltipText}
      className={`flex items-center gap-1 rounded-full px-2.5 py-1 text-xs font-medium capitalize ${statusStyles[status]} ${status === QueueStatus.Failed && errorMessage ? "cursor-help" : ""}`}
    >
      {status}
    </div>
  );
};

export default StatusBadge;
