import React from "react";

import { QueueStatus } from "@/types";

interface StatusBadgeProps {
  status: QueueStatus;
}

const statusStyles: Record<QueueStatus, string> = {
  [QueueStatus.IDLE]: "bg-gray-500/20 text-gray-400",
  [QueueStatus.PROCESSING]: "bg-blue-500/20 text-blue-400 animate-pulse",
  [QueueStatus.COMPLETED]: "bg-emerald-500/20 text-emerald-400",
  [QueueStatus.FAILED]: "bg-red-500/20 text-red-400",
  [QueueStatus.PAUSED]: "bg-amber-500/20 text-amber-400",
};

const statusDescriptions: Record<QueueStatus, string> = {
  [QueueStatus.IDLE]: "Waiting in queue to be processed",
  [QueueStatus.PROCESSING]: "Currently being generated by Gemini",
  [QueueStatus.COMPLETED]: "Successfully completed",
  [QueueStatus.FAILED]: "Generation failed - check Gemini for errors",
  [QueueStatus.PAUSED]: "Paused - will resume when queue starts",
};

export const StatusBadge: React.FC<StatusBadgeProps> = ({ status }) => {
  return (
    <div
      title={statusDescriptions[status]}
      className={`flex items-center gap-1 rounded-md px-2 py-0.5 text-[9px] font-black uppercase tracking-widest ${statusStyles[status]}`}
    >
      {status}
    </div>
  );
};

export default StatusBadge;
