/**
 * @fileoverview Error codes used throughout the application
 */

export const ERROR_CODES = {
  // Authentication Errors
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_EXPIRED: "AUTH_TOKEN_EXPIRED",
  AUTH_TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  AUTH_REFRESH_TOKEN_INVALID: "AUTH_REFRESH_TOKEN_INVALID",
  AUTH_OTP_INVALID: "AUTH_OTP_INVALID",
  AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_OAUTH_FAILED: "AUTH_OAUTH_FAILED",

  // Subscription Errors
  SUB_NOT_FOUND: "SUB_NOT_FOUND",
  SUB_EXPIRED: "SUB_EXPIRED",
  SUB_INSUFFICIENT_CREDITS: "SUB_INSUFFICIENT_CREDITS",
  SUB_WEBHOOK_INVALID: "SUB_WEBHOOK_INVALID",
  SUB_PAYMENT_FAILED: "SUB_PAYMENT_FAILED",

  // Validation Errors
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_INPUT: "INVALID_INPUT",

  // Rate Limiting
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",

  // General Errors
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
} as const;
